export const series = {
  seriesMapProto: [
    {
      date: "JANUARY 2023",
      series: [
        {
          id: 5255,
          name: "Bangladesh Premier League 2023",
          startDt: "1672963200000",
          endDt: "1676505600000",
        },
        {
          id: 4994,
          name: "SA20, 2023",
          startDt: "1673308800000",
          endDt: "1676160000000",
        },
        {
          id: 5106,
          name: "International League T20, 2023",
          startDt: "1673568000000",
          endDt: "1676160000000",
        },
      ],
    },
    {
      date: "FEBRUARY 2023",
      series: [
        {
          id: 5441,
          name: "Pakistan Super League, 2023",
          startDt: "1676246400000",
          endDt: "1679184000000",
        },
      ],
    },
    {
      date: "MAY 2023",
      series: [
        {
          id: 5246,
          name: "T20 Blast 2023",
          startDt: "1684540800000",
          endDt: "1689379200000",
        },
      ],
    },
    {
      date: "AUGUST 2023",
      series: [
        {
          id: 5924,
          name: "The Hundred Mens Competition 2023",
          startDt: "1690848000000",
          endDt: "1693094400000",
        },
      ],
    },
  ],
  appIndex: {
    seoTitle: "Current Running Cricket Series - Cricbuzz | Cricbuzz.com",
    webURL: "www.cricbuzz.com/cricket-series/",
  },
};

export const pointsTable = {
  pointsTable: [
    {
      groupName: "Teams",
      pointsTableInfo: [
        {
          teamId: 1263,
          teamName: "PC",
          matchesPlayed: 10,
          matchesWon: 7,
          matchesLost: 3,
          points: 31,
          nrr: "+0.927",
          teamFullName: "Pretoria Capitals",
          teamMatches: [
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1673481600000",
              result: "Won by 23 runs",
              opponentSName: "SEC",
              matchId: 57760,
              matchName: "3rd Match",
              winner: 1263,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1673654400000",
              result: "Won by 37 runs",
              opponentSName: "SEC",
              matchId: 57781,
              matchName: "6th Match",
              winner: 1263,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1673913600000",
              result: "Loss by 6 runs",
              opponentSName: "JSK",
              matchId: 57804,
              matchName: "11th Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1674000000000",
              result: "Won by 6 wkts",
              opponentSName: "JSK",
              matchId: 57811,
              matchName: "13th Match",
              winner: 1263,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1674172800000",
              result: "Won by 8 wkts",
              opponentSName: "DSG",
              matchId: 57823,
              matchName: "15th Match",
              winner: 1263,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1674345600000",
              result: "Loss by 6 wkts",
              opponentSName: "PR",
              matchId: 57837,
              matchName: "18th Match",
              winner: 1235,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1674432000000",
              result: "Won by 52 runs",
              opponentSName: "MICT",
              matchId: 57846,
              matchName: "20th Match",
              winner: 1263,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1675468800000",
              result: "Won by 1 wkt",
              opponentSName: "MICT",
              matchId: 57879,
              matchName: "26th Match",
              winner: 1263,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1675555200000",
              result: "Loss by 151 runs",
              opponentSName: "DSG",
              matchId: 57886,
              matchName: "28th Match",
              winner: 1242,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1675728000000",
              result: "Won by 59 runs",
              opponentSName: "PR",
              matchId: 57895,
              matchName: "30th Match",
              winner: 1263,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1675814400000",
              result: "Won by 29 runs",
              opponentSName: "PR",
              matchId: 57902,
              matchName: "1st Semi-Final",
              winner: 1263,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1676073600000",
              result:
                "SA20 final postponed to February 12 due to persistent rain",
              opponentSName: "SEC",
              matchId: 57923,
              matchName: "Final",
              winner: 1,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1676160000000",
              result: "Loss by 4 wkts",
              opponentSName: "SEC",
              matchId: 65777,
              matchName: "Final (Rescheduled Match)",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
          ],
          form: ["L", "W", "W", "A", "L"],
          teamImageId: 248443,
          teamQualifyStatus: "Q",
        },
        {
          teamId: 1249,
          teamName: "JSK",
          matchesPlayed: 10,
          matchesWon: 6,
          matchesLost: 3,
          noRes: 1,
          points: 27,
          nrr: "-0.111",
          teamFullName: "Joburg Super Kings",
          teamMatches: [
            {
              opponent: "Durban Super Giants",
              startdt: "1673395200000",
              result: "Won by 16 runs",
              opponentSName: "DSG",
              matchId: 57753,
              matchName: "2nd Match",
              winner: 1249,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1673568000000",
              result: "Loss by 7 wkts",
              opponentSName: "PR",
              matchId: 57767,
              matchName: "4th Match",
              winner: 1235,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1673654400000",
              result: "Loss by 7 wkts",
              opponentSName: "MICT",
              matchId: 57783,
              matchName: "7th Match",
              winner: 1228,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1673913600000",
              result: "Won by 6 runs",
              opponentSName: "PC",
              matchId: 57804,
              matchName: "11th Match",
              winner: 1249,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1674000000000",
              result: "Loss by 6 wkts",
              opponentSName: "PC",
              matchId: 57811,
              matchName: "13th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1674259200000",
              result: "Won by 5 wkts",
              opponentSName: "SEC",
              matchId: 57832,
              matchName: "17th Match",
              winner: 1249,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1674518400000",
              result: "Won by 8 wkts",
              opponentSName: "DSG",
              matchId: 57858,
              matchName: "22nd Match",
              winner: 1249,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1675382400000",
              result: "No result",
              opponentSName: "PR",
              matchId: 57865,
              matchName: "24th Match",
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1675555200000",
              result: "Won by 24 runs",
              opponentSName: "SEC",
              matchId: 57881,
              matchName: "27th Match",
              winner: 1249,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1675641600000",
              result: "Won by 76 runs",
              opponentSName: "MICT",
              matchId: 57888,
              matchName: "29th Match",
              winner: 1249,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1675900800000",
              result: "Loss by 14 runs",
              opponentSName: "SEC",
              matchId: 57914,
              matchName: "2nd Semi-Final",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
          ],
          form: ["W", "N", "W", "W", "L"],
          teamImageId: 248422,
          teamQualifyStatus: "Q",
        },
        {
          teamId: 1256,
          teamName: "SEC",
          matchesPlayed: 10,
          matchesWon: 4,
          matchesLost: 5,
          noRes: 1,
          points: 19,
          nrr: "+0.316",
          teamFullName: "Sunrisers Eastern Cape",
          teamMatches: [
            {
              opponent: "Pretoria Capitals",
              startdt: "1673481600000",
              result: "Loss by 23 runs",
              opponentSName: "PC",
              matchId: 57760,
              matchName: "3rd Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1673654400000",
              result: "Loss by 37 runs",
              opponentSName: "PC",
              matchId: 57781,
              matchName: "6th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1673827200000",
              result: "Won by 4 wkts",
              opponentSName: "MICT",
              matchId: 57790,
              matchName: "9th Match",
              winner: 1256,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1674000000000",
              result: "Won by 2 wkts",
              opponentSName: "MICT",
              matchId: 57809,
              matchName: "12th Match",
              winner: 1256,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1674086400000",
              result: "Won by 5 wkts",
              opponentSName: "PR",
              matchId: 57818,
              matchName: "14th Match",
              winner: 1256,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1674259200000",
              result: "Loss by 5 wkts",
              opponentSName: "JSK",
              matchId: 57832,
              matchName: "17th Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1674345600000",
              result: "Won by 124 runs",
              opponentSName: "DSG",
              matchId: 57844,
              matchName: "19th Match",
              winner: 1256,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1674518400000",
              result: "Loss by 5 wkts",
              opponentSName: "PR",
              matchId: 57851,
              matchName: "21st Match",
              winner: 1235,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1675382400000",
              result: "No result (due to rain)",
              opponentSName: "DSG",
              matchId: 57872,
              matchName: "25th Match",
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1675555200000",
              result: "Loss by 24 runs",
              opponentSName: "JSK",
              matchId: 57881,
              matchName: "27th Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1675900800000",
              result: "Won by 14 runs",
              opponentSName: "JSK",
              matchId: 57914,
              matchName: "2nd Semi-Final",
              winner: 1256,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1676073600000",
              result:
                "SA20 final postponed to February 12 due to persistent rain",
              opponentSName: "PC",
              matchId: 57923,
              matchName: "Final",
              winner: 1,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1676160000000",
              result: "Won by 4 wkts",
              opponentSName: "PC",
              matchId: 65777,
              matchName: "Final (Rescheduled Match)",
              winner: 1256,
              opponentId: 1263,
              opponentImageId: 248443,
            },
          ],
          form: ["N", "L", "W", "A", "W"],
          teamImageId: 248451,
          teamQualifyStatus: "Q",
        },
        {
          teamId: 1235,
          teamName: "PR",
          matchesPlayed: 10,
          matchesWon: 4,
          matchesLost: 5,
          noRes: 1,
          points: 19,
          nrr: "-0.293",
          teamFullName: "Paarl Royals",
          teamMatches: [
            {
              opponent: "MI Cape Town",
              startdt: "1673308800000",
              result: "Loss by 8 wkts",
              opponentSName: "MICT",
              matchId: 57746,
              matchName: "1st Match",
              winner: 1228,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1673568000000",
              result: "Won by 7 wkts",
              opponentSName: "JSK",
              matchId: 57767,
              matchName: "4th Match",
              winner: 1235,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1673740800000",
              result: "Loss by 27 runs",
              opponentSName: "DSG",
              matchId: 57788,
              matchName: "8th Match",
              winner: 1242,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1673913600000",
              result: "Won by 10 runs",
              opponentSName: "DSG",
              matchId: 57797,
              matchName: "10th Match",
              winner: 1235,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1674086400000",
              result: "Loss by 5 wkts",
              opponentSName: "SEC",
              matchId: 57818,
              matchName: "14th Match",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1674259200000",
              result: "Loss by 13 runs",
              opponentSName: "MICT",
              matchId: 57830,
              matchName: "16th Match",
              winner: 1228,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1674345600000",
              result: "Won by 6 wkts",
              opponentSName: "PC",
              matchId: 57837,
              matchName: "18th Match",
              winner: 1235,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1674518400000",
              result: "Won by 5 wkts",
              opponentSName: "SEC",
              matchId: 57851,
              matchName: "21st Match",
              winner: 1235,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1675382400000",
              result: "No result",
              opponentSName: "JSK",
              matchId: 57865,
              matchName: "24th Match",
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1675728000000",
              result: "Loss by 59 runs",
              opponentSName: "PC",
              matchId: 57895,
              matchName: "30th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1675814400000",
              result: "Loss by 29 runs",
              opponentSName: "PC",
              matchId: 57902,
              matchName: "1st Semi-Final",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
          ],
          form: ["W", "W", "N", "L", "L"],
          teamImageId: 248440,
          teamQualifyStatus: "Q",
        },
        {
          teamId: 1242,
          teamName: "DSG",
          matchesPlayed: 10,
          matchesWon: 4,
          matchesLost: 5,
          noRes: 1,
          points: 19,
          nrr: "-0.319",
          teamFullName: "Durban Super Giants",
          teamMatches: [
            {
              opponent: "Joburg Super Kings",
              startdt: "1673395200000",
              result: "Loss by 16 runs",
              opponentSName: "JSK",
              matchId: 57753,
              matchName: "2nd Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1673568000000",
              result: "Won by 5 wkts",
              opponentSName: "MICT",
              matchId: 57774,
              matchName: "5th Match",
              winner: 1242,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1673740800000",
              result: "Won by 27 runs",
              opponentSName: "PR",
              matchId: 57788,
              matchName: "8th Match",
              winner: 1242,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1673913600000",
              result: "Loss by 10 runs",
              opponentSName: "PR",
              matchId: 57797,
              matchName: "10th Match",
              winner: 1235,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1674172800000",
              result: "Loss by 8 wkts",
              opponentSName: "PC",
              matchId: 57823,
              matchName: "15th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1674345600000",
              result: "Loss by 124 runs",
              opponentSName: "SEC",
              matchId: 57844,
              matchName: "19th Match",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1674518400000",
              result: "Loss by 8 wkts",
              opponentSName: "JSK",
              matchId: 57858,
              matchName: "22nd Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "MI Cape Town",
              startdt: "1675296000000",
              result: "Won by 5 wkts",
              opponentSName: "MICT",
              matchId: 57860,
              matchName: "23rd Match",
              winner: 1242,
              opponentId: 1228,
              opponentImageId: 248432,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1675382400000",
              result: "No result (due to rain)",
              opponentSName: "SEC",
              matchId: 57872,
              matchName: "25th Match",
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1675555200000",
              result: "Won by 151 runs",
              opponentSName: "PC",
              matchId: 57886,
              matchName: "28th Match",
              winner: 1242,
              opponentId: 1263,
              opponentImageId: 248443,
            },
          ],
          form: ["L", "L", "W", "N", "W"],
          teamImageId: 248403,
          teamQualifyStatus: "E",
        },
        {
          teamId: 1228,
          teamName: "MICT",
          matchesPlayed: 10,
          matchesWon: 3,
          matchesLost: 7,
          points: 13,
          nrr: "-0.500",
          teamFullName: "MI Cape Town",
          teamMatches: [
            {
              opponent: "Paarl Royals",
              startdt: "1673308800000",
              result: "Won by 8 wkts",
              opponentSName: "PR",
              matchId: 57746,
              matchName: "1st Match",
              winner: 1228,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1673568000000",
              result: "Loss by 5 wkts",
              opponentSName: "DSG",
              matchId: 57774,
              matchName: "5th Match",
              winner: 1242,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1673654400000",
              result: "Won by 7 wkts",
              opponentSName: "JSK",
              matchId: 57783,
              matchName: "7th Match",
              winner: 1228,
              opponentId: 1249,
              opponentImageId: 248422,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1673827200000",
              result: "Loss by 4 wkts",
              opponentSName: "SEC",
              matchId: 57790,
              matchName: "9th Match",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Sunrisers Eastern Cape",
              startdt: "1674000000000",
              result: "Loss by 2 wkts",
              opponentSName: "SEC",
              matchId: 57809,
              matchName: "12th Match",
              winner: 1256,
              opponentId: 1256,
              opponentImageId: 248451,
            },
            {
              opponent: "Paarl Royals",
              startdt: "1674259200000",
              result: "Won by 13 runs",
              opponentSName: "PR",
              matchId: 57830,
              matchName: "16th Match",
              winner: 1228,
              opponentId: 1235,
              opponentImageId: 248440,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1674432000000",
              result: "Loss by 52 runs",
              opponentSName: "PC",
              matchId: 57846,
              matchName: "20th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Durban Super Giants",
              startdt: "1675296000000",
              result: "Loss by 5 wkts",
              opponentSName: "DSG",
              matchId: 57860,
              matchName: "23rd Match",
              winner: 1242,
              opponentId: 1242,
              opponentImageId: 248403,
            },
            {
              opponent: "Pretoria Capitals",
              startdt: "1675468800000",
              result: "Loss by 1 wkt",
              opponentSName: "PC",
              matchId: 57879,
              matchName: "26th Match",
              winner: 1263,
              opponentId: 1263,
              opponentImageId: 248443,
            },
            {
              opponent: "Joburg Super Kings",
              startdt: "1675641600000",
              result: "Loss by 76 runs",
              opponentSName: "JSK",
              matchId: 57888,
              matchName: "29th Match",
              winner: 1249,
              opponentId: 1249,
              opponentImageId: 248422,
            },
          ],
          form: ["W", "L", "L", "L", "L"],
          teamImageId: 248432,
          teamQualifyStatus: "E",
        },
      ],
    },
  ],
  appIndex: {
    seoTitle: "SA20, 2023 Points Table | Cricbuzz.com",
    webURL: "www.cricbuzz.com/cricket-series/4994/sa20-2023/points-table",
  },
};
