export const LeagueMap = {
  "Argentine Liga Profesional de Fútbol": "ligaprofesionalargentina",
  "Australian A-League": "australiacup",
  "Brazilian Serie A": "brasileirãosériea",
  "Chinese Super League": "chinesesuperleague",
  "Dutch Eredivisie": "eredivisie",
  "English Premier League": "premierleague",
  "French Ligue 1": "ligue1ubereats",
  "German Bundesliga": "bundesliga",
  "Italian Serie A": "seriea",
  "Japanese J League": "j.league",
  "Malaysian Super League": "ligasupermalaysia",
  "Mexican Liga BBVA MX": "ligabbvamxclausura",
  "Portuguese Liga": "ligaportugal",
  "Russian Premier League": "russianpremierleague",
  "Spanish Primera División": "laliga",
  "Turkish Super Lig": "süperlig",
  saudiprofessionalleague: "saudiprofessionalleague",
};
